version: '3.8'

services:
  db:
    image: postgres:15
    container_name: swift_db_server
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: swift_bank_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  db_test:
    image: postgres:15
    container_name: swift_db_test_server
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: swift_bank_test_db
    ports:
      - "55432:55432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data

  app:
    build: ./app
    container_name: swift_app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - db_test
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: root
      DB_PASSWORD: admin
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: disable
      MODE: ${MODE}
    volumes:
      - app_data:/app/data

volumes:
  pgdata:
  pgdata_test:
  app_data:
