version: '3.8'

services:
  db:
    image: postgres:15
    container_name: swift_db_server
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: swift_bank_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: ./app
    container_name: swift_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: admin
      DB_NAME: swift_bank_db
      DB_SSLMODE: disable

volumes:
  pgdata:
